port: 4001

title: CV | Victor Li
description:  Victor Li's CV
url: 
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
